services:
  postgres_db:
    extends:
      file: .docker/docker-compose.yml
      service: postgres_db
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - find-a-friend-network

  redis:
    extends:
      file: .docker/docker-compose.yml
      service: redis
    networks:
      - find-a-friend-network

  mailpit:
    extends:
      file: .docker/docker-compose.yml
      service: mailpit
    volumes:
      - mailpit-data:/data
    networks:
      - find-a-friend-network

volumes:
  postgresql_data:
    driver: local
  mailpit-data:
    driver: local

networks:
  find-a-friend-network:
    name: find-a-friend-network
    driver: bridge
