services:
    api:
        container_name: find-a-friend-api
        build:
            dockerfile: Dockerfile
            target: base
        entrypoint: sh -c "npm ci && npm run dev:server:watch"
        ports:
            - 3333:3333
        volumes:
            - ./:/home/node/app
        networks:
            - find-a-friend-network
        depends_on:
            - postgres_db
            - redis

    api-queue-worker:
        container_name: find-a-friend-api-queue-worker
        build:
            dockerfile: Dockerfile
            target: base
        entrypoint: sh -c "npm run dev:queue"
        networks:
            - find-a-friend-network
        depends_on:
            - api

    postgres_db:
        image: bitnami/postgresql:16.2.0
        ports:
            - 5432:5432
        environment:
            - POSTGRESQL_USERNAME=docker
            - POSTGRESQL_PASSWORD=docker
        volumes:
            - postgresql_data:/bitnami/postgresql
        networks:
            - find-a-friend-network

    redis:
        image: bitnami/redis:7.0.15
        ports:
            - 6379:6379
        environment:
            - ALLOW_EMPTY_PASSWORD=true
        networks:
            - find-a-friend-network

volumes:
    postgresql_data:
        driver: local

networks:
    find-a-friend-network:
        name: find-a-friend-network
        driver: bridge
