services:
  postgres_db:
    image: bitnami/postgresql:16.2.0
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - find-a-friend-network

  redis:
    image: bitnami/redis:7.0.15
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    networks:
      - find-a-friend-network

  mailpit:
    image: axllent/mailpit
    environment:
      MP_DATA_FILE: /data/mailpit.db
      MP_UI_BIND_ADDR: 0.0.0.0:8025
      MP_SMTP_AUTH_ACCEPT_ANY: "true"
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
      TZ: America/Sao_Paulo
    ports:
      - 8025:8025
    volumes:
      - mailpit-data:/data
    networks:
      - find-a-friend-network

volumes:
  postgresql_data:
    driver: local
  mailpit-data:
    driver: local

networks:
  find-a-friend-network:
    name: find-a-friend-network
    driver: bridge
