services:
    api:
        container_name: find-a-friend-api
        build:
            dockerfile: Dockerfile
            target: base
        entrypoint: sh -c "npm ci && npm run dev:watch"
        ports:
            - 3333:3333
        volumes:
            - ./:/home/node/app
